// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation
import Get
import URLQueryEncoder

extension Paths.Alerts {
    public func regionID(_ regionID: String) -> WithRegionID {
        WithRegionID(path: "\(path)/\(regionID)")
    }

    public struct WithRegionID {
        /// Path: `/api/v3/alerts/{regionId}`
        public let path: String

        /// Статус області/регіону/громади
        public var get: Request<[AlertRegionModel]> {
            .get(path)
        }
    }
}
