// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation
import Get
import URLQueryEncoder

extension Paths.Alerts {
    public var regionHistory: RegionHistory {
        RegionHistory(path: path + "/regionHistory")
    }

    public struct RegionHistory {
        /// Path: `/api/v3/alerts/regionHistory`
        public let path: String

        /// Отримати останніх 25 тривог регіону
        public func get(regionID: String? = nil) -> Request<[RegionAlarmsHistory]> {
            .get(path, query: makeGetQuery(regionID))
        }

        private func makeGetQuery(_ regionID: String?) -> [(String, String?)] {
            let encoder = URLQueryEncoder()
            encoder.encode(regionID, forKey: "regionId")
            return encoder.items
        }
    }
}
