// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation
import Get
import URLQueryEncoder

extension Paths.Alerts {
    public var status: Status {
        Status(path: path + "/status")
    }

    public struct Status {
        /// Path: `/api/v3/alerts/status`
        public let path: String

        /// Перевірка номеру останньої дії. Використовувати для перевірки необхідності оновлювати дані
        public var get: Request<AlertModification> {
            .get(path)
        }
    }
}
