// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation
import Get
import URLQueryEncoder

extension Paths {
    public static var alerts: Alerts {
        Alerts(path: "/api/v3/alerts")
    }

    public struct Alerts {
        /// Path: `/api/v3/alerts`
        public let path: String

        /// Області, регіони та громади з тривогами
        public var get: Request<[AlertRegionModel]> {
            .get(path)
        }
    }
}
