// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation

public struct Alert: Codable {
    public var regionID: String?
    public var regionType: V2RegionType?
    public var type: AlertType?
    public var lastUpdate: Date?

    public init(regionID: String? = nil, regionType: V2RegionType? = nil, type: AlertType? = nil, lastUpdate: Date? = nil) {
        self.regionID = regionID
        self.regionType = regionType
        self.type = type
        self.lastUpdate = lastUpdate
    }

    private enum CodingKeys: String, CodingKey {
        case regionID = "regionId"
        case regionType
        case type
        case lastUpdate
    }
}
