// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation

public struct AlertDuration: Codable {
    public var id: Int?
    public var regionID: String?
    public var parentRegionID: String?
    public var regionName: String?
    public var startDate: Date?
    public var endDate: Date?
    public var duration: TimeSpan?
    public var alertType: AlertType?
    public var isContinue: Bool?

    public init(id: Int? = nil, regionID: String? = nil, parentRegionID: String? = nil, regionName: String? = nil, startDate: Date? = nil, endDate: Date? = nil, duration: TimeSpan? = nil, alertType: AlertType? = nil, isContinue: Bool? = nil) {
        self.id = id
        self.regionID = regionID
        self.parentRegionID = parentRegionID
        self.regionName = regionName
        self.startDate = startDate
        self.endDate = endDate
        self.duration = duration
        self.alertType = alertType
        self.isContinue = isContinue
    }

    private enum CodingKeys: String, CodingKey {
        case id
        case regionID = "regionId"
        case parentRegionID = "parentRegionId"
        case regionName
        case startDate
        case endDate
        case duration
        case alertType
        case isContinue
    }
}
