// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation

public struct RegionsViewModel: Codable {
    public var states: [RegionViewModel]?

    public init(states: [RegionViewModel]? = nil) {
        self.states = states
    }
}
