// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation

public struct RegionViewModel: Codable {
    public var regionID: String?
    public var regionName: String?
    public var regionType: V2RegionType?
    public var regionChildIDs: [RegionViewModel]?

    public init(regionID: String? = nil, regionName: String? = nil, regionType: V2RegionType? = nil, regionChildIDs: [RegionViewModel]? = nil) {
        self.regionID = regionID
        self.regionName = regionName
        self.regionType = regionType
        self.regionChildIDs = regionChildIDs
    }

    private enum CodingKeys: String, CodingKey {
        case regionID = "regionId"
        case regionName
        case regionType
        case regionChildIDs = "regionChildIds"
    }
}
