// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation

public enum AlertType: String, Codable, CaseIterable {
    case unknown = "UNKNOWN"
    case air = "AIR"
    case artillery = "ARTILLERY"
    case urbanFights = "URBAN_FIGHTS"
    case chemical = "CHEMICAL"
    case nuclear = "NUCLEAR"
    case info = "INFO"
}
