// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation

public struct AlertModification: Codable {
    public var lastActionIndex: Int?

    public init(lastActionIndex: Int? = nil) {
        self.lastActionIndex = lastActionIndex
    }
}
