// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation

public struct AlertRegionModel: Codable {
    public var regionID: String?
    public var regionType: V2RegionType?
    public var regionName: String?
    public var lastUpdate: Date?
    public var activeAlerts: [Alert]?

    public init(regionID: String? = nil, regionType: V2RegionType? = nil, regionName: String? = nil, lastUpdate: Date? = nil, activeAlerts: [Alert]? = nil) {
        self.regionID = regionID
        self.regionType = regionType
        self.regionName = regionName
        self.lastUpdate = lastUpdate
        self.activeAlerts = activeAlerts
    }

    private enum CodingKeys: String, CodingKey {
        case regionID = "regionId"
        case regionType
        case regionName
        case lastUpdate
        case activeAlerts
    }
}
