// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation

public struct RegionAlarmModel: Codable {
    public var regionID: String?
    public var startDate: Date?
    public var endDate: Date?
    public var duration: TimeSpan?
    public var alertType: AlertType?
    public var regionName: String?
    public var isContinue: Bool?

    public init(regionID: String? = nil, startDate: Date? = nil, endDate: Date? = nil, duration: TimeSpan? = nil, alertType: AlertType? = nil, regionName: String? = nil, isContinue: Bool? = nil) {
        self.regionID = regionID
        self.startDate = startDate
        self.endDate = endDate
        self.duration = duration
        self.alertType = alertType
        self.regionName = regionName
        self.isContinue = isContinue
    }

    private enum CodingKeys: String, CodingKey {
        case regionID = "regionId"
        case startDate
        case endDate
        case duration
        case alertType
        case regionName
        case isContinue
    }
}
