// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation

public enum V2RegionType: String, Codable, CaseIterable {
    case state = "State"
    case district = "District"
    case community = "Community"
    case null = "Null"
}
