// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation
import Get
import URLQueryEncoder

extension Paths {
    public static var webhook: Webhook {
        Webhook(path: "/api/v3/webhook")
    }

    public struct Webhook {
        /// Path: `/api/v3/webhook`
        public let path: String

        /// Підписка на WebHook про нові сирени та їх відбій
        public func post(_ body: WebHookModel? = nil) -> Request<Void> {
            .post(path, body: body)
        }

        /// Оновлення WebHook посилання про нові сирени та їх відбій
        public func patch(_ body: WebHookModel? = nil) -> Request<Void> {
            .patch(path, body: body)
        }

        /// Відписка на WebHook про нові сирени та їх відбій
        public func delete(_ body: WebHookModel? = nil) -> Request<Void> {
            .delete(path, body: body)
        }
    }
}
