// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation
import Get
import URLQueryEncoder

extension Paths.Alerts {
    public var allHistory: AllHistory {
        AllHistory(path: path + "/allHistory")
    }

    public struct AllHistory {
        /// Path: `/api/v3/alerts/allHistory`
        public let path: String

        /// Отримати історію усіх тривог
        public var get: Request<[StateAlarmsHolder]> {
            .get(path)
        }
    }
}
